# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for linux/drivers/platform/arm64
#
# This dir should only include drivers for EC-like devices.
#

obj-$(CONFIG_EC_ACER_ASPIRE1)	+= acer-aspire1-ec.o
obj-$(CONFIG_EC_HUAWEI_GAOKUN)	+= huawei-gaokun-ec.o
obj-$(CONFIG_EC_LENOVO_YOGA_C630) += lenovo-yoga-c630.o
obj-$(CONFIG_EC_QCOM_X1E_IT8987) += qcom-x1e-it8987.o
